#!/bin/bash

find . -type f -iname "*.gif" | while IFS= read -r file; do
    # Fayl adını path-dən çıxarır
    name="${file##*/}"
    # .gif uzantısını silir (case-insensitive)
    echo "${name%.[Gg][Ii][Ff]}"
done | sort -f

